// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAZAmVavI6_H0wBQzRpAn_350SiIdDAck',
    appId: '1:458490123543:web:c523fe25d05eb925779352',
    messagingSenderId: '458490123543',
    projectId: 'daraz-clone-7b875',
    authDomain: 'daraz-clone-7b875.firebaseapp.com',
    storageBucket: 'daraz-clone-7b875.appspot.com',
    measurementId: 'G-1QM2PBMZ36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA512YNkYhF3bfhKSuvahVSOqZkoaVJDm8',
    appId: '1:458490123543:android:bc4d464d5430679d779352',
    messagingSenderId: '458490123543',
    projectId: 'daraz-clone-7b875',
    storageBucket: 'daraz-clone-7b875.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmcpDTYQgFRrL-S4T1FToO0xqhDC7ydFs',
    appId: '1:458490123543:ios:f70ae39fb9aee624779352',
    messagingSenderId: '458490123543',
    projectId: 'daraz-clone-7b875',
    storageBucket: 'daraz-clone-7b875.appspot.com',
    androidClientId: '458490123543-jp4osvedfgc1t4so9goog1cuh4c72r34.apps.googleusercontent.com',
    iosClientId: '458490123543-et6p2rl2pcbbg27ifu3f6h2eoqe4noav.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPannel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmcpDTYQgFRrL-S4T1FToO0xqhDC7ydFs',
    appId: '1:458490123543:ios:23f7af2cc841949f779352',
    messagingSenderId: '458490123543',
    projectId: 'daraz-clone-7b875',
    storageBucket: 'daraz-clone-7b875.appspot.com',
    androidClientId: '458490123543-jp4osvedfgc1t4so9goog1cuh4c72r34.apps.googleusercontent.com',
    iosClientId: '458490123543-c60huugrt9lkpatb20ksfe3tnm43ro9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPannel.RunnerTests',
  );
}
